spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${EMAIL}
    password:  ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: false


server:
  port: 8088

logging:
  level:
    root: info
    org.springframework.amqp: debug
